<div style='float:left;'><strong>Today: </strong> <?php echo date('F d, Y');?></div>
<div>
	<ul>
		<!--<li><a href="/portal/payroll/index.php?item=tssummary">Timesheet</a></li>-->
		<li><a href="#" id='settings'>Settings</a>
			<div class='submenu' style='width:207px;'><a href='/portal/payroll/index.php?item=staffrate' id='hrrate'>Staff Rate</a>
				<a href='/portal/payroll/index.php?item=cutoff' id='cutoffdate'>Cut off</a><a href='/portal/payroll/index.php?item=holidays' id='holi'>Holidays</a></div>
		</li>
		<li><a href="index.php">Home</a></li></ul>
	
</div>
