<style type="text/css">
	#staffrate {
		top: 50px;
		left: 70%;
		/*margin:0 auto;*/
		margin-left: -150px;
		width: 270px;
	}
	
	#holidays {
		top: 0;
		left: 60%;
		/*margin:0 auto;*/
		margin-left: -150px;
		width: 450px;
	}
	
	#cutoff {
		top: 20px;
		left: 85%;
		/*margin:0 auto;*/
		margin-left: 0;
		width: 100px;
	}
	
	#staffrate, #cutoff, #holidays {
		display: none;
		position: fixed;
		background-color: #EEE;
		color: #333;
		border: 1px solid black;
		padding: 12px;
	}
	
	.jqmOverlay { background-color: #000; }
	
	* html #staffrate, #cutoff, #holidays {
		 position: absolute;
		 top: expression((document.documentElement.scrollTop || document.body.scrollTop) + Math.round(17 * (document.documentElement.offsetHeight || document.body.clientHeight) / 100) + 'px');
	}
</style>
<h2><?php echo $this->subtitle;?>: <?php echo $this->daterange;?></h2>

				
	<div class='topbar'>
		<div style='float:right;width:auto;font-weight:bold;padding-right:8px'>
		<?php //if($this->view == 'tssummary'):?>
		<!--<span><a href='?item=tssummary&dir=left&cnt=<?php echo $this->left_cnt;?>' id='prev'>&lt;</a></span>
		<span><a href='?item=tssummary&dir=right&cnt=<?php echo $this->right_cnt;?>' id='next'>&gt;</a></span>-->
		<span><a href='?dir=left&cutoff=<?php echo $this->prev;?>' title='Previous' id='prev'>&lt;</a></span>
		<span><a href='?dir=right&cutoff=<?php echo $this->next;?>' title='Next' id='next'>&gt;</a></span>
		<span style='margin-left:20px;'><a href='#' id='reload'>Reload</a></span>
		<?php //else:?>
		<!--<span style='margin-left:20px;'><a href='#' id='reload'>Reload</a></span>
		<span style='margin-left:20px;'>Save</span>-->
		<?php //endif;?>
		
			
		</div>
	</div>

<div id="container" style="float:left;width:100%;">
<div id="loadingimg" style="float:left;display:block; width:100%; text-align:center; top:100px; font:16px Arial;">
	<img src="/adhoc/php/images/loading.gif" border=0 height='64' width='64'><br>
	Loading... Please wait
</div>
</div>

<!-- rate per hr display -->
<div id='staffrate'>Please wait...</div>
<div id='cutoff'>Please wait...</div>
<div id='holidays'>Please wait...</div>
<?php echo $this->viewname;?>