<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-GB">
<head>
	<title></title>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
	<!--<meta name="robots" content="index, follow" />
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />-->
	<link rel="stylesheet" type="text/css" href="/portal/aclog/css/screen3.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="/portal/aclog/css/styles.css" />
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="/portal/js/jquery.js"><\/script>')</script>
	<script type="text/javascript" src="/portal/aclog/js/logger.js"></script>
	<script type="text/javascript" src="/portal/ticketmgmt/js/jqModal.js"></script>
	<!--<script type="text/javascript" src="/portal/payroll/index.php?item=daterange"></script>-->
	<style type="text/css">
	#timesheet {
		display: none;
		position: fixed;
		top: 0;
		left: 50%;
		/*margin:0 auto;*/
		margin-left:-46%; /*-450px;*/
		width:90%; /*850px;*/
		
		background-color: #EEE;
		color: #333;
		border: 1px solid black;
		padding: 12px;
	}
	
	.jqmOverlay { background-color: #000; }
	
	* html #timesheet {
		 position: absolute;
		 top: expression((document.documentElement.scrollTop || document.body.scrollTop) + Math.round(17 * (document.documentElement.offsetHeight || document.body.clientHeight) / 100) + 'px');
	}
	</style>
</head>
<body>

		
	<div id="staff" style="float:left;width:100%;padding-right:20px;">
		

		
		<div id="tabular">
			<table summary="ActivityListing" id="myactivity">
		
			<tbody>
           	<tr>				
				<th scope="col" style='width:8%'>Start Time</th>
				<th scope="col" style='width:10%'>Time Ended</th>
				<th scope="col" style='width:9%'>Elapsed Time</th>
				<th scope="col" style='width:9%'>Last Started</th>
				<th scope="col" style="width:52%;">Activity</th>
				<th scope="col" style='width:5%'>Type</th>
				<th scope="col" style='width:7%'>Set Status</th>
			  
			</tr>
			
			</tbody>
                    
            </table>
		</div>
    </div>
	
	<!-- timesheet display -->
	<div id='timesheet'>Please wait...</div>
</body>
</html>